/* SaveScores.java - generated by ACUCOBOL-GT v11.0.0 */
/* Generated Thu Jan 15 10:57:11 2026 */

package org.example;

import com.acucorp.acucobolgt.*;

public class SaveScores {

	private CVM cvm;

	public SaveScores() {
		super();
		cvm = CVM.GET_INSTANCE();
		cvm.setErrorsOut( "errFile" );
		cvm.setConfigFile("config");
		cvm.initialize( "SaveScores" );

	}

	public CVM getCVM() {
		return cvm;
	}

	public void Cancel( String name ) {
		try {
			if( cvm != null ) {
				cvm.cancelProgram( name );
			}
		} catch( Exception e ) {
			e.printStackTrace();
		}

	}

	public int SaveScores_CVM_main( String USERNAME_IN,
	                                 Short COVERED_IN ) {

		int retVal = 0;

		try {

			Object params[] = { USERNAME_IN,
		                                 COVERED_IN };
			// cvm.logParams( params );
			CALL_OPTIONS callOptions = new CALL_OPTIONS();
			callOptions.setOption("linkage_signature", "X20S");
			// callOptions.setOption("debug_method", "2");

			retVal = cvm.callProgram( "temp/org/example/SaveScores", params, callOptions );
		} catch( Exception e ) {
			e.printStackTrace();
		}
		return retVal;

	}

	protected void finalize() throws Throwable {
		cvm.shutdown();
	}
}
